
language: cpp

compiler:
    - gcc

notifications:
    email:
        - padronas@stanford.edu
  
branches:
    only:
        - feature_TravisCI

#before_install:
#    - sudo apt-get update
#    - sudo apt-get install -qq python-numpy python-scipy python-matplotlib
  
install:
    - ./configure
    # Add environmental variables according to the configure step
    - export SU2_RUN="/usr/local/bin"
    - export SU2_HOME="/home/travis/build/su2code/SU2"
    - export PATH=$PATH:$SU2_RUN
    - export PYTHONPATH=$PYTHONPATH:$SU2_RUN
    - make -j 4
    - cd QuickStart/
  
# run test
script:  
    #- python automatic_regression.py
    - SU2_CFD inv_NACA0012.cfg

