# Continous Integration setup for SU2.
# Tests on the develop and master branch in both serial and parallel.
language: cpp

matrix:
    include:
        - compiler: g++
            # Serial build and test
            env:
                - CONFIGURE_COMMAND='./configure --prefix=/usr/local CXXFLAGS="-O3"'
                - TEST_SCRIPT = serial_regression.py
        - compiler: g++
            # Parallel build and test
            env: 
                - CONFIGURE_COMMAND='./configure --enable-mpi --with-cc=`which mpicc` --with-cxx=`which mpicxx` --prefix=/usr/local CXXFLAGS="-O3"'
                - TEST_SCRIPT = parallel_regression.py

notifications:
    email:
        - padronas@stanford.edu
  
branches:
    only:
        - feature_TravisCI

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy mpich2
    - echo $CONFIGURE_COMMAND

install:
    # Think test matrix compiling code in serial and parallel.
    - $CONFIGURE_COMMAND
    # Add environmental variables according to the configure step
    - export SU2_RUN="/usr/local/bin"
    # Find out what SU2_HOME is used for.
    - export SU2_HOME="/home/travis/build/su2code/SU2"
    - export PATH=$PATH:$SU2_RUN
    - export PYTHONPATH=$PYTHONPATH:$SU2_RUN
    - make -j 8
    - sudo make install

before_script:
    - git clone https://github.com/su2code/TestCases.git
    - cd TestCases/
    - git checkout feature_TravisCI
    - cat $TEST_SCRIPT

# run test
script:  
    - python $TEST_SCRIPT
