# Continous Integration setup for SU2.
# Tests on the develop and master branch in both serial and parallel.

language: cpp

compiler:
    - g++


notifications:
    email:
        - padronas@stanford.edu
  
branches:
    only:
        - feature_TravisCI

before_install:
    # install the necessary packages
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy mpich2
    # Define the serial and parallel configuration commands
    - export SERIAL='./configure --prefix=/usr/local CXXFLAGS="-O3"'
    - export PARALLEL='./configure --enable-mpi --with-cc=`which mpicc` --with-cxx=`which mpicxx` --prefix=/usr/local CXXFLAGS="-O3"'
    - echo $CONFIGURE_COMMAND

env:
    # Set the build matrix
    # Serial build
    - CONFIGURE_COMMAND=$SERIAL
    # Parallel build 
    - CONFIGURE_COMMAND=$PARALLEL

install:
    - echo $CONFIGURE_COMMAND
    - $CONFIGURE_COMMAND
    # Add environmental variables according to the configure step
    # Can I add this after the install.
    - export SU2_RUN="/usr/local/bin"
    # Find out what SU2_HOME is used for.
    - export SU2_HOME="/home/travis/build/su2code/SU2"
    - export PATH=$PATH:$SU2_RUN
    - export PYTHONPATH=$PYTHONPATH:$SU2_RUN
    - make -j 8
    - sudo make install

before_script:
    # Get the test cases
    - git clone https://github.com/su2code/TestCases.git
    - cd TestCases/
    - git checkout feature_TravisCI

script:
    # run the tests
    - if [ $CONFIGURE_COMMAND == $SERIAL ]; then python serial_regression.py; fi
    - if [ $CONFIGURE_COMMAND == $PARALLEL ]; then python parallel_regression.py; fi


