
language: cpp

compiler:
    - gcc

notifications:
    email:
        - padronas@stanford.edu
  
branches:
    only:
        - feature_TravisCI

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy
    - sudo apt-cache search .
    #- sudo apt-get install mpich2
    - sudo apt-get install openmpi-bin #openmpi1.5-bin
    - which mpicc
    - which mpicxx
    - which mpirun
    - which mpiexec

install:
    - ./configure --enable-mpi --with-cc=/usr/bin/mpicc --with-cxx=/usr/bin/mpicxx --prefix=/usr/local # This is the default prefix anyways
    # Add environmental variables according to the configure step
    #- sudo mkdir /usr/local/SU2
    - export SU2_RUN="/usr/local/bin"
    # Find out what SU2_HOME is used for.
    - export SU2_HOME="/home/travis/build/su2code/SU2"
    - export PATH=$PATH:$SU2_RUN
    - export PYTHONPATH=$PYTHONPATH:$SU2_RUN
    - make -j 8
    - sudo make install
    - cd QuickStart/
  
# run test
script:  
    #- python automatic_regression.py
    #- SU2_CFD inv_NACA0012.cfg
    - parallel_computation.py -f inv_NACA0012.cfg -n 4

